### PR TITLE
answers for lesson 8

### PR DESCRIPTION
**Pull request by aboubacar108**

### CODE REVIEW

**Review by aschey — CHANGES_REQUESTED** [review]
@aboubacar108 I think this PR is backward. Looks like you're trying to merge `main` into `week8` instead of merging `week8` into `main`.

**Comment by aboubacar108** [comment]
> @aboubacar108 I think this PR is backward. Looks like you're trying to merge `main` into `week8` instead of merging `week8` into `main`.

Thank you for your feedback. How do I undo this?

**Comment by aboubacar108** [comment]
> > @aboubacar108 I think this PR is backward. Looks like you're trying to merge `main` into `week8` instead of merging `week8` into `main`.
> 
> Thank you for your feedback. How do I undo this?

Should I just close the PR and start it again?

**Comment by aschey** [comment]
> > > @aboubacar108 I think this PR is backward. Looks like you're trying to merge `main` into `week8` instead of merging `week8` into `main`.
> > 
> > Thank you for your feedback. How do I undo this?
> 
> Should I just close the PR and start it again?

Yep that works

**Pull request closed without merging**
